# Generated by Django 4.2 on 2026-08-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_comida', models.CharField(max_length=100)),
                ('calificacion', models.IntegerField()),
                ('abierto', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-calificacion'],
            },
        ),
    ]
