# Generated by Django 6.1 on 2026-09-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=3),
        ),
    ]
